### ISSUE TITLE
Plotting test performance

### ISSUE THREAD

**Issue by samieti02** [deepmedic/deepmedic#172]
Hello Sir,

Is there a possibility to also integrate "plotTestingProgress" ?

DSC (Full Segment) is empty for training after running the code python `plotTrainingProgress.py examples/output/logs/trainSessionConf.txt -d`  . Did I miss something?

Thanks
Sir

**Comment by Kamnitsask** [comment]
Sorry for the late reply, I am currently focusing on writing up by PhD Thesis and time is ridiculously limited.

Thank you, for the suggestion on plotting test results. It would be nice to implement a collection of plotting/evalution scripts, but currently this is a lower priority than focusing on the main model/components. I will leave this issue open for now, perhaps I ll find time in later months for this.

---
Regarding the DSC being empty for training, this happens if you have disabled:
performFullInferenceOnValidationImagesEveryFewEpochs = False

in the trainConfig, or somehow the training logs are corrupted.

**Comment by samieti02** [comment]
I also set the parameter `performFullInferenceOnValidationImagesEveryFewEpochs = True`, and other parameters to True, but for the training in DSC (Full) nothing appears, but for validation, we can see a graph

**Comment by Kamnitsask** [comment]
I now understand what you meant.

The DSC on whole volumes is never computed for training cases. It's too expensive and there is no point (I think). That's why it's empy.
