### ISSUE TITLE
Predef and stable learning rate

### ISSUE THREAD

**Issue by samieti02** [deepmedic/deepmedic#181]
Hi Sir,
can you please give us more details about the technique of choosing the learning rate. Why do you suggest to train first the learning rate with the parameter stable  and then to switch to predef and use the values from the peaks (top or bottom of the mountain) of stable for the parameter predef. Which method it is? Why this method will give better results? 
Thanks

**Comment by Kamnitsask** [comment]
Belated reply, sorry:

Selection of learning rate is empirical, and is data-specific and task-specific. That's why I suggest the above process if the user wishes to configure it themselves.

Closing the issue as it's not a technical for DM, but rather a discussion about good practice in configuring models (which is an open question :)).
