### ISSUE TITLE
Model File Selection for Inference

### ISSUE THREAD

**Issue by stalhabukhari** [deepmedic/deepmedic#198]
Hi!

This is a pretty simple question, but for completeness I wanted to know how you go about the process.

Which model file do you select for testing? Is it the final model? A more familiar and plausible method (for me) is to select the model parameters corresponding to minimum *epoch-averaged* validation **loss**, but here those values are not logged on to TensorBoard.

Thanking in anticipation.

Best Regards,
Talha

**Comment by Kamnitsask** [comment]
Hi Talha, sorry for the delay, it s been a very busy month.

I cannot give a "definite" answer because I think there is no flawless way to do it (see in the end for the reason).

Your suggestion sounds reasonable. I do not often look at "loss", I tend to look at other accuracy metrics. E.g. you could use the DSC validation metric for this, which is logged.

But, what I tend to use myself is, I never really pick 1 model. Whenever I want to extract "confident" conclusions, I always run multiple training sessions from multiple seeds (eg x3 for small experiments or x5+ for more serious ones), train them till convergence (eg 35 epochs by default), and then just take the average performance of all these models at the final iteration (end of epoch 35, saved as "final" in the model name). Dealing with a single seed and trying to extract conclusions from a single seed is not something I recommend as good practice.

If you would wish to have 1 single prediction, then I do the same as above, but create an ensemble of all the models, and then I provide the prediction of the ensemble (eg to my clinical collaborators).

Reason I dont trust 1 model:
Validation data are often little. And chances are they wont represent the "test" data well enough. So, a model that is "best" for validation data (the best checkpoint) may merely be a good fit for validation data but not for "test" data. Averaging multiple models or ensembling them does not suffer from this.

I hope the above helps

**Comment by stalhabukhari** [comment]
Dear Dr Kamnitsas,

Thank you for the insight, and for your time.

Kind Regards,
Talha
